# Generated by Django 4.2.30 on 2026-05-15 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_code', models.CharField(max_length=20, unique=True, verbose_name='Mã lớp')),
                ('class_name', models.CharField(max_length=50, verbose_name='Tên lớp')),
                ('intake_year', models.IntegerField(verbose_name='Năm nhập học')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_classes', to='academics.department', verbose_name='Ngành')),
            ],
            options={
                'verbose_name': 'Lớp sinh hoạt',
                'verbose_name_plural': 'Lớp sinh hoạt',
                'ordering': ['-intake_year', 'class_code'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True, verbose_name='MSSV')),
                ('full_name', models.CharField(max_length=100, verbose_name='Họ tên')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Ngày sinh')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Số điện thoại')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='student_photos/', verbose_name='Ảnh khuôn mặt')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang học')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='students.studentclass', verbose_name='Lớp sinh hoạt')),
            ],
            options={
                'verbose_name': 'Sinh viên',
                'verbose_name_plural': 'Sinh viên',
                'ordering': ['student_class', 'full_name'],
            },
        ),
    ]
