# Generated by Django 4.2.30 on 2026-05-25 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_teacher_avatar_upload_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['teacher_id'], 'verbose_name': 'Giảng viên', 'verbose_name_plural': 'Giảng viên'},
        ),
    ]
