# Generated by Django 4.2.30 on 2026-06-17 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_teacher_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("admin", "Quản Trị Viên"), ("teacher", "Giảng Viên")],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("permissions", models.JSONField(default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Phân quyền vai trò",
                "verbose_name_plural": "Phân quyền vai trò",
            },
        ),
    ]
