# Generated by Django 4.2.30 on 2026-05-26 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('courses', '0004_remove_course_room_number_add_course_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sessions', models.IntegerField(default=0, verbose_name='Tổng buổi đã học')),
                ('present_count', models.IntegerField(default=0, verbose_name='Số buổi có mặt')),
                ('absent_count', models.IntegerField(default=0, verbose_name='Số buổi vắng')),
                ('late_count', models.IntegerField(default=0, verbose_name='Số buổi đi trễ')),
                ('attendance_rate', models.FloatField(default=0.0, verbose_name='Tỉ lệ có mặt (%)')),
                ('absent_rate', models.FloatField(default=0.0, verbose_name='Tỉ lệ vắng (%)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lúc')),
                ('course_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_reports', to='courses.courseclass', verbose_name='Lớp học phần')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_reports', to='students.student', verbose_name='Sinh viên')),
            ],
            options={
                'verbose_name': 'Báo cáo chuyên cần',
                'verbose_name_plural': 'Báo cáo chuyên cần',
                'ordering': ['course_class', 'student'],
                'unique_together': {('student', 'course_class')},
            },
        ),
    ]
