# Generated by Django 4.2.30 on 2026-05-15 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('accounts', '0001_initial'),
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=20, unique=True, verbose_name='Mã học phần')),
                ('course_name', models.CharField(max_length=200, verbose_name='Tên học phần')),
                ('credits', models.IntegerField(default=3, verbose_name='Số tín chỉ')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='academics.department', verbose_name='Ngành')),
            ],
            options={
                'verbose_name': 'Học phần',
                'verbose_name_plural': 'Học phần',
                'ordering': ['course_code'],
            },
        ),
        migrations.CreateModel(
            name='CourseClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_code', models.CharField(max_length=30, verbose_name='Mã lớp HP')),
                ('max_students', models.IntegerField(default=40, verbose_name='Sĩ số tối đa')),
                ('total_sessions', models.IntegerField(default=15, verbose_name='Tổng số buổi')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_classes', to='courses.course', verbose_name='Học phần')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_classes', to='academics.semester', verbose_name='Học kỳ')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_classes', to='accounts.teacher', verbose_name='Giảng viên')),
            ],
            options={
                'verbose_name': 'Lớp học phần',
                'verbose_name_plural': 'Lớp học phần',
                'ordering': ['semester', 'class_code'],
                'unique_together': {('course', 'semester', 'class_code')},
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đăng ký')),
                ('is_active', models.BooleanField(default=True, verbose_name='Còn học')),
                ('course_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.courseclass', verbose_name='Lớp học phần')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student', verbose_name='Sinh viên')),
            ],
            options={
                'verbose_name': 'Đăng ký học phần',
                'verbose_name_plural': 'Đăng ký học phần',
                'ordering': ['course_class', 'student'],
                'unique_together': {('course_class', 'student')},
            },
        ),
    ]
