# Generated by Django 4.2.30 on 2026-05-25 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_teacher_options'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='room_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Số phòng'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courses_taught', to='accounts.teacher', verbose_name='Giảng viên'),
        ),
    ]
