# Generated by Django 4.2.30 on 2026-05-25 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_room_number_course_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='teacher',
        ),
    ]
