# Generated by Django 4.2.30 on 2026-05-25 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
        ('courses', '0003_remove_course_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='room_number',
        ),
        migrations.AddField(
            model_name='course',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='schedules.room', verbose_name='Phòng học'),
        ),
    ]
