# Generated by Django 4.2.30 on 2026-05-25 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_semester_unique_constraint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicyear',
            options={'ordering': ['-start_date'], 'verbose_name': 'Năm học', 'verbose_name_plural': 'Năm học'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['code'], 'verbose_name': 'Ngành', 'verbose_name_plural': 'Ngành'},
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'ordering': ['code'], 'verbose_name': 'Khoa', 'verbose_name_plural': 'Khoa'},
        ),
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ['-academic_year__start_date', 'semester_num'], 'verbose_name': 'Học kỳ', 'verbose_name_plural': 'Học kỳ'},
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='end_date',
            field=models.DateField(verbose_name='Ngày kết thúc'),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Năm học'),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='start_date',
            field=models.DateField(verbose_name='Ngày bắt đầu'),
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='Mã ngành'),
        ),
        migrations.AlterField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='academics.faculty', verbose_name='Khoa'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Tên ngành'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='Mã khoa'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Tên khoa'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='academics.academicyear', verbose_name='Năm học'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='end_date',
            field=models.DateField(verbose_name='Ngày kết thúc'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester_num',
            field=models.IntegerField(verbose_name='Học kỳ'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='start_date',
            field=models.DateField(verbose_name='Ngày bắt đầu'),
        ),
    ]
