# Generated by Django 4.2.30 on 2026-05-15 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(max_length=20, unique=True, verbose_name='Mã phòng')),
                ('building', models.CharField(blank=True, max_length=50, verbose_name='Tòa nhà')),
                ('capacity', models.IntegerField(default=40, verbose_name='Sức chứa')),
                ('has_camera', models.BooleanField(default=False, verbose_name='Có camera điểm danh')),
            ],
            options={
                'verbose_name': 'Phòng học',
                'verbose_name_plural': 'Phòng học',
                'ordering': ['building', 'room_code'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(2, 'Thứ Hai'), (3, 'Thứ Ba'), (4, 'Thứ Tư'), (5, 'Thứ Năm'), (6, 'Thứ Sáu'), (7, 'Thứ Bảy'), (8, 'Chủ Nhật')], verbose_name='Thứ trong tuần')),
                ('start_period', models.IntegerField(verbose_name='Tiết bắt đầu')),
                ('end_period', models.IntegerField(verbose_name='Tiết kết thúc')),
                ('date', models.DateField(verbose_name='Ngày học')),
                ('session_number', models.IntegerField(verbose_name='Buổi thứ')),
                ('course_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='courses.courseclass', verbose_name='Lớp học phần')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='schedules.room', verbose_name='Phòng học')),
            ],
            options={
                'verbose_name': 'Lịch học',
                'verbose_name_plural': 'Lịch học',
                'ordering': ['date', 'start_period'],
                'unique_together': {('course_class', 'date')},
            },
        ),
    ]
