# Generated by Django 4.2.30 on 2026-06-14 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['campus', 'building', 'room_code'], 'verbose_name': 'Phòng học', 'verbose_name_plural': 'Phòng học'},
        ),
        migrations.AddField(
            model_name='room',
            name='campus',
            field=models.CharField(blank=True, default='Cơ sở chính', max_length=50, verbose_name='Cơ sở'),
        ),
    ]
