# Generated by Django 4.2.30 on 2026-05-15 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noti_type', models.CharField(choices=[('absent_warning', 'Cảnh báo vắng (> 20%)'), ('absent_danger', 'Nguy hiểm vắng (> 40%)')], max_length=20, verbose_name='Loại cảnh báo')),
                ('absent_count', models.IntegerField(verbose_name='Số buổi vắng')),
                ('total_sessions', models.IntegerField(verbose_name='Tổng số buổi đã học')),
                ('absent_percent', models.FloatField(verbose_name='Tỉ lệ vắng (%)')),
                ('is_read', models.BooleanField(default=False, verbose_name='Đã đọc')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tạo')),
                ('course_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='courses.courseclass', verbose_name='Lớp học phần')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='students.student', verbose_name='Sinh viên')),
            ],
            options={
                'verbose_name': 'Cảnh báo vắng mặt',
                'verbose_name_plural': 'Cảnh báo vắng mặt',
                'ordering': ['-created_at'],
            },
        ),
    ]
