# Generated by Django 4.2.30 on 2026-05-26 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_course_room_number_add_course_room'),
        ('students', '0001_initial'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notification',
            unique_together={('student', 'course_class')},
        ),
    ]
