# Generated by Django 4.2.30 on 2026-05-15 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Bắt đầu lúc')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Kết thúc lúc')),
                ('status', models.CharField(choices=[('open', 'Đang mở'), ('closed', 'Đã đóng')], default='open', max_length=10, verbose_name='Trạng thái')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('course_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='courses.courseclass', verbose_name='Lớp học phần')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Giảng viên tạo')),
                ('schedule', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_session', to='schedules.schedule', verbose_name='Buổi lịch học')),
            ],
            options={
                'verbose_name': 'Buổi điểm danh',
                'verbose_name_plural': 'Buổi điểm danh',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Có mặt'), ('absent', 'Vắng'), ('late', 'Đi trễ')], default='absent', max_length=10, verbose_name='Trạng thái')),
                ('method', models.CharField(choices=[('face', 'Nhận diện khuôn mặt'), ('manual', 'Thủ công')], default='face', max_length=10, verbose_name='Phương thức')),
                ('confidence', models.FloatField(default=0.0, verbose_name='Độ chính xác')),
                ('timestamp', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm nhận diện')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Ghi chú')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='attendance.attendancesession', verbose_name='Buổi điểm danh')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='students.student', verbose_name='Sinh viên')),
            ],
            options={
                'verbose_name': 'Bản ghi điểm danh',
                'verbose_name_plural': 'Bản ghi điểm danh',
                'ordering': ['session', 'student'],
                'unique_together': {('session', 'student')},
            },
        ),
    ]
